- uri: template://custom-provisioners/service-port-with-microcks
  type: service-port
  description: Outputs a hostname and port for connecting to another workload, generates a Microcks mock if not found.
  init: |
    hostname: {{ .Params.workload }}
    port: {{ .Params.port }}
  outputs: |
    {{ $w := (index .WorkloadServices .Params.workload) }}
    {{ if or (not $w) (not $w.ServiceName) }}
    hostname: localhost
    {{ else }}
    hostname: {{ .Init.hostname }}
    {{ end }}
    port: {{ .Init.port }}
  expected_outputs:
    - hostname
    - port
  supported_params:
    - workload
    - port
  services: |
    {{ $w := (index .WorkloadServices .Params.workload) }}
    {{ if or (not $w) (not $w.ServiceName) }}
    {{ .Init.hostname }}-mock:
      image: quay.io/microcks/microcks-cli:latest
      restart: always
      entrypoint:
        - "microcks-cli"
        - "import"
        - "/resources/{{ .Params.workload }}-openapi.yaml:true"
        - "--microcksURL=http://microcks:8080/api"
        - "--insecure"
        - "--keycloakClientId=foo"
        - "--keycloakClientSecret=bar"
      volumes:
      - type: bind
        source: ./resources
        target: /resources
        read_only: true
    {{ end }}